"""Adjustment on sorting Table

Revision ID: 6f89c26a273a
Revises: a8c8ba7007ad
Create Date: 2024-11-17 23:36:09.579432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f89c26a273a'
down_revision: Union[str, None] = 'a8c8ba7007ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sorting', sa.Column('sortingId', sa.UUID(), nullable=False))
    op.drop_column('sorting', 'sortindId')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sorting', sa.Column('sortindId', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('sorting', 'sortingId')
    # ### end Alembic commands ###
