"""Adjustment on return_request Table

Revision ID: 854aafca0fd7
Revises: 1b3cbb19800f
Create Date: 2024-11-16 02:10:49.187780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '854aafca0fd7'
down_revision: Union[str, None] = '1b3cbb19800f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('return_request', sa.Column('returnRequestResult', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('return_request', 'returnRequestResult')
    # ### end Alembic commands ###
