"""Adjustment on defect Table

Revision ID: bf6c82197da6
Revises: 854aafca0fd7
Create Date: 2024-11-16 10:06:18.292593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf6c82197da6'
down_revision: Union[str, None] = '854aafca0fd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('defect', sa.Column('defectStatus', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('defect', 'defectStatus')
    # ### end Alembic commands ###
