from .customer import Customer
from .defect import Defect
from .employee import Employee
from .productType import ProductType
from .product import Product
from .repair import Repair
from .requestApproval import RequestApproval
from .returnRequest import ReturnRequest
from .sorting import Sorting